import { DiscoveryClip, ScoutProfile, ModerationQueueItem } from './types';

// NOTE: These are placeholder videos for development/demo purposes only
// In production, videos will be:
// 1. Real user-uploaded sports clips from Supabase Storage
// 2. Moderated and approved content
// 3. Tagged by athletes with wholesome categories
//
// The current placeholder videos are test files that will play in any browser
// Replace these with actual sports training clips when connecting to Supabase

const BASE_DISCOVERY_CLIPS = [
  {
    id: 'disc-1',
    athleteId: 'athlete-1',
    athleteName: 'Maya Johnson',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya',
    athleteAge: 16,
    athleteLocation: 'Seattle, WA',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    caption: 'First goal in varsity! Been working on this shot for months 🎯⚽',
    tags: ['first_time', 'milestone', 'dedication'],
    upvotes: 347,
    views: 1204,
    duration: 45,
    createdAt: '2025-11-08T10:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-2',
    athleteId: 'athlete-2',
    athleteName: 'Carlos Rivera',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    athleteAge: 17,
    athleteLocation: 'Austin, TX',
    sport: 'Basketball',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    caption: 'Game-winning three at the buzzer! State semifinals 🏀🔥',
    tags: ['game_winning', 'milestone', 'technique'],
    upvotes: 892,
    views: 3421,
    duration: 38,
    createdAt: '2025-11-08T05:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-3',
    athleteId: 'athlete-3',
    athleteName: 'Aisha Patel',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    athleteAge: 15,
    athleteLocation: 'Boston, MA',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400',
    caption: 'Back on the field after ACL recovery! 6 months of hard work 💪',
    tags: ['comeback', 'breakthrough', 'dedication'],
    upvotes: 1243,
    views: 5102,
    duration: 52,
    createdAt: '2025-11-07T18:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-4',
    athleteId: 'athlete-4',
    athleteName: 'Tyler Chen',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tyler',
    athleteAge: 16,
    athleteLocation: 'Portland, OR',
    sport: 'Basketball',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=400',
    caption: 'Helped opponent up after hard foul. Respect first 🤝',
    tags: ['sportsmanship', 'inclusive'],
    upvotes: 567,
    views: 2145,
    duration: 28,
    createdAt: '2025-11-07T14:00:00Z',
    moderationStatus: 'approved',
  },
  // SPONSORED AD
  {
    id: 'sponsored-1',
    athleteId: 'sponsor-hbo',
    athleteName: 'HBO Sports',
    athleteAvatar: 'https://logo.clearbit.com/hbo.com',
    athleteAge: 0,
    athleteLocation: 'New York, NY',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
    caption: 'Stream the world\'s biggest sports moments live on Max. Your front row to greatness. 🎬',
    tags: [],
    upvotes: 0,
    views: 0,
    duration: 15,
    createdAt: '2025-11-08T00:00:00Z',
    moderationStatus: 'approved',
    isSponsored: true,
    sponsorName: 'HBO',
    sponsorLogo: 'https://logo.clearbit.com/hbo.com',
  },
  {
    id: 'disc-5',
    athleteId: 'athlete-5',
    athleteName: 'Emma Williams',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    athleteAge: 17,
    athleteLocation: 'Denver, CO',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400',
    caption: 'Team assist drill - chemistry is everything! ⚽👥',
    tags: ['teamwork', 'technique'],
    upvotes: 423,
    views: 1789,
    duration: 41,
    createdAt: '2025-11-07T06:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-6',
    athleteId: 'athlete-6',
    athleteName: 'Jake Morrison',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jake',
    athleteAge: 18,
    athleteLocation: 'Miami, FL',
    sport: 'Basketball',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    caption: 'Ankle breaker crossover in the championship game! 🏀',
    tags: ['technique', 'game_winning'],
    upvotes: 1456,
    views: 6782,
    duration: 22,
    createdAt: '2025-11-07T04:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-7',
    athleteId: 'athlete-7',
    athleteName: 'Sofia Martinez',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    athleteAge: 16,
    athleteLocation: 'Los Angeles, CA',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    caption: 'Bicycle kick goal! My coach said it was impossible ⚽✨',
    tags: ['technique', 'milestone', 'breakthrough'],
    upvotes: 2341,
    views: 8901,
    duration: 35,
    createdAt: '2025-11-07T02:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-8',
    athleteId: 'athlete-8',
    athleteName: 'Devin Jackson',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Devin',
    athleteAge: 17,
    athleteLocation: 'Chicago, IL',
    sport: 'Basketball',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=400',
    caption: 'Windmill dunk at 5\'10"! Height is just a number 🔥',
    tags: ['breakthrough', 'dedication', 'first_time'],
    upvotes: 987,
    views: 4532,
    duration: 18,
    createdAt: '2025-11-06T22:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-9',
    athleteId: 'athlete-9',
    athleteName: 'Lily Anderson',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lily',
    athleteAge: 15,
    athleteLocation: 'San Diego, CA',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400',
    caption: 'First time as team captain! Leading by example 💪⚽',
    tags: ['first_time', 'milestone', 'sportsmanship'],
    upvotes: 654,
    views: 2876,
    duration: 42,
    createdAt: '2025-11-06T20:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-10',
    athleteId: 'athlete-10',
    athleteName: 'Marcus Thompson',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    athleteAge: 18,
    athleteLocation: 'Houston, TX',
    sport: 'Basketball',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    caption: 'Triple-double in playoffs! First in school history 🏀📊',
    tags: ['milestone', 'breakthrough', 'dedication'],
    upvotes: 1823,
    views: 7234,
    duration: 48,
    createdAt: '2025-11-06T18:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-11',
    athleteId: 'athlete-11',
    athleteName: 'Hannah Kim',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hannah',
    athleteAge: 16,
    athleteLocation: 'Phoenix, AZ',
    sport: 'Soccer',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    caption: 'Free kick from 30 yards out! Top corner perfection ⚽🎯',
    tags: ['technique', 'game_winning'],
    upvotes: 1109,
    views: 5432,
    duration: 26,
    createdAt: '2025-11-06T16:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-12',
    athleteId: 'athlete-12',
    athleteName: 'Isaiah Brown',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isaiah',
    athleteAge: 17,
    athleteLocation: 'Atlanta, GA',
    sport: 'Basketball',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=400',
    caption: 'Passing drills with my little brother. Family first! 👨‍👦🏀',
    tags: ['teamwork', 'inclusive', 'sportsmanship'],
    upvotes: 789,
    views: 3211,
    duration: 37,
    createdAt: '2025-11-06T14:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-13',
    athleteId: 'athlete-13',
    athleteName: 'Mia Rodriguez',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
    athleteAge: 15,
    athleteLocation: 'Dallas, TX',
    sport: 'Soccer',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400',
    caption: 'Hat trick in state finals! Dreams do come true ⚽⚽⚽',
    tags: ['milestone', 'game_winning', 'breakthrough'],
    upvotes: 2567,
    views: 9876,
    duration: 51,
    createdAt: '2025-11-06T12:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-14',
    athleteId: 'athlete-14',
    athleteName: 'Jordan Lee',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    athleteAge: 18,
    athleteLocation: 'Philadelphia, PA',
    sport: 'Basketball',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    caption: 'Comeback from torn ACL. 8 months of grinding 💪🏀',
    tags: ['comeback', 'dedication', 'breakthrough'],
    upvotes: 1876,
    views: 6543,
    duration: 44,
    createdAt: '2025-11-06T10:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-15',
    athleteId: 'athlete-15',
    athleteName: 'Isabella Garcia',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    athleteAge: 16,
    athleteLocation: 'San Jose, CA',
    sport: 'Soccer',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    caption: 'Juggling practice paying off! 100+ touches ⚽✨',
    tags: ['technique', 'dedication'],
    upvotes: 543,
    views: 2134,
    duration: 29,
    createdAt: '2025-11-06T08:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-16',
    athleteId: 'athlete-16',
    athleteName: 'Ethan White',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
    athleteAge: 17,
    athleteLocation: 'Detroit, MI',
    sport: 'Basketball',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=400',
    caption: 'No-look pass for the assist! Chemistry with my teammate 🔥',
    tags: ['teamwork', 'technique'],
    upvotes: 923,
    views: 4123,
    duration: 21,
    createdAt: '2025-11-06T06:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-17',
    athleteId: 'athlete-17',
    athleteName: 'Chloe Davis',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe',
    athleteAge: 15,
    athleteLocation: 'Nashville, TN',
    sport: 'Soccer',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400',
    caption: 'First goal after switching positions! Adaptability is key ⚽🔄',
    tags: ['first_time', 'breakthrough', 'dedication'],
    upvotes: 687,
    views: 2987,
    duration: 33,
    createdAt: '2025-11-06T04:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-18',
    athleteId: 'athlete-18',
    athleteName: 'Noah Wilson',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Noah',
    athleteAge: 18,
    athleteLocation: 'Indianapolis, IN',
    sport: 'Basketball',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    caption: 'Teaching kids at local community center. Giving back 🏀❤️',
    tags: ['inclusive', 'sportsmanship', 'teamwork'],
    upvotes: 1234,
    views: 5678,
    duration: 46,
    createdAt: '2025-11-06T02:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-19',
    athleteId: 'athlete-19',
    athleteName: 'Olivia Taylor',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    athleteAge: 16,
    athleteLocation: 'Charlotte, NC',
    sport: 'Soccer',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    caption: 'Penalty kick to win the tournament! Ice in my veins ⚽❄️',
    tags: ['game_winning', 'milestone', 'technique'],
    upvotes: 1765,
    views: 7123,
    duration: 24,
    createdAt: '2025-11-06T00:00:00Z',
    moderationStatus: 'approved',
  },
  {
    id: 'disc-20',
    athleteId: 'athlete-20',
    athleteName: 'Liam Martinez',
    athleteAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Liam',
    athleteAge: 17,
    athleteLocation: 'Columbus, OH',
    sport: 'Basketball',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=400',
    caption: 'Summer league highlights! Ready for senior year 🏀🔥',
    tags: ['technique', 'dedication'],
    upvotes: 876,
    views: 3456,
    duration: 39,
    createdAt: '2025-11-05T22:00:00Z',
    moderationStatus: 'approved',
  },
];

const WHOLESOME_TAGS = new Set(['sportsmanship', 'inclusive']);

export const MOCK_DISCOVERY_CLIPS: DiscoveryClip[] = BASE_DISCOVERY_CLIPS.map((clip) => {
  const base = clip as Partial<DiscoveryClip> & {
    id: string;
    athleteId: string;
    athleteName: string;
    sport: string;
    videoUrl: string;
    caption: string;
    createdAt: string;
    tags?: string[];
    upvotes?: number;
    views?: number;
    duration?: number;
  };

  const tags = base.tags ?? [];
  const upvotes = base.upvotes ?? 0;
  const usernameSource = base.athleteName || base.athleteId;
  const slugifiedUsername = usernameSource
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  const athleteUsername = base.athleteUsername ?? (slugifiedUsername || base.athleteId);
  const isWholesome = base.isWholesome ?? tags.some((tag) => WHOLESOME_TAGS.has(tag));

  return {
    ...base,
    athleteUsername,
    tags,
    upvotes,
    contentRating: base.contentRating ?? 'sfw',
    isWholesome,
    comments: base.comments ?? Math.floor(upvotes / 8),
    shares: base.shares ?? Math.floor(upvotes / 12),
    views: base.views ?? Math.max(upvotes * 3, 0),
    hasUpvoted: base.hasUpvoted ?? false,
    isBookmarked: base.isBookmarked ?? false,
    isSponsored: base.isSponsored ?? false,
    sponsorName: base.sponsorName,
    sponsorLogo: base.sponsorLogo,
    moderationStatus: base.moderationStatus ?? 'approved',
  };
});

export const MOCK_SCOUTS: ScoutProfile[] = [
  {
    id: 'scout-1',
    name: 'Coach Sarah Mitchell',
    organization: 'Stanford University',
    role: 'Women\'s Soccer Recruiting Coordinator',
    sports: ['Soccer'],
    verified: true,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahMitchell',
  },
  {
    id: 'scout-2',
    name: 'Mike Thompson',
    organization: 'Duke University',
    role: 'Men\'s Basketball Assistant Coach',
    sports: ['Basketball'],
    verified: true,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MikeThompson',
  },
  {
    id: 'scout-3',
    name: 'Lisa Rodriguez',
    organization: 'UCLA',
    role: 'Multi-Sport Talent Scout',
    sports: ['Soccer', 'Basketball'],
    verified: true,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LisaRodriguez',
  },
];

export const MOCK_MODERATION_QUEUE: ModerationQueueItem[] = [
  {
    id: 'mod-1',
    clipId: 'clip-pending-1',
    athleteId: 'athlete-6',
    athleteName: 'Jordan Lee',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400',
    caption: 'First time breaking 5 minutes in the mile! 🏃‍♂️',
    tags: ['first_time', 'milestone'],
    sport: 'Soccer',
    submittedAt: '2025-11-08T09:30:00Z',
    moderationStatus: 'pending',
  },
  {
    id: 'mod-2',
    clipId: 'clip-pending-2',
    athleteId: 'athlete-7',
    athleteName: 'Sam Kim',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a26?w=400',
    caption: 'Crossover move I learned from YouTube 🏀',
    tags: ['technique', 'dedication'],
    sport: 'Basketball',
    submittedAt: '2025-11-08T09:15:00Z',
    moderationStatus: 'pending',
  },
];
