import type { DiscoveryClip } from './types'

export const MOCK_DISCOVERY_CLIPS: DiscoveryClip[] = [
  // TOP 4 CLIPS - MATCHING DASHBOARD "TOP POSTS TODAY"
  {
    id: '1', // Matches dashboard post ID
    videoUrl: '/soccer-player-practicing-ball-control.mp4',
    thumbnailUrl: '/soccer-player-practicing-ball-control.png',
    caption: 'Working on my first touch control! Finally getting consistent with both feet 🔥 #FirstTouchFriday',
    athleteId: 'user1',
    athleteName: 'Alex Chen',
    athleteUsername: 'alex_chen',
    athleteAvatar: '/asian-athlete.png',
    athleteAge: 17,
    athleteLocation: 'Lincoln High School',
    sport: 'Soccer',
    sportId: 3,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'midwest',
    upvotes: 24,
    comments: 8,
    shares: 3,
    views: 1234,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'training', 'first-touch'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(), // 2 hours ago
  },
  {
    id: '2', // Matches dashboard post ID
    videoUrl: '/basketball-player-jumping-for-dunk.mp4',
    thumbnailUrl: '/basketball-player-jumping-for-dunk.png',
    caption: 'Vertical jump training paying off! New personal record today 💪',
    athleteId: 'user2',
    athleteName: 'Maria Rodriguez',
    athleteUsername: 'maria_rodriguez',
    athleteAvatar: '/latina-coach.png',
    athleteAge: 18,
    athleteLocation: 'City Gym',
    sport: 'Basketball',
    sportId: 1,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'south',
    upvotes: 31,
    comments: 12,
    shares: 5,
    views: 2156,
    hasUpvoted: true,
    isBookmarked: true,
    tags: ['training', 'vertical-jump', 'personal-record'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 14400000).toISOString(), // 4 hours ago
  },
  {
    id: '3', // Matches dashboard post ID
    videoUrl: '/volleyball-player-serving-ball.mp4',
    thumbnailUrl: '/volleyball-player-serving-ball.png',
    caption: 'Serve accuracy drill - hitting the corners consistently now! Coach says I\'m ready for varsity 🏐',
    athleteId: 'user3',
    athleteName: 'James Thompson',
    athleteUsername: 'james_thompson',
    athleteAvatar: '/black-athlete.png',
    athleteAge: 16,
    athleteLocation: 'Roosevelt High',
    sport: 'Volleyball',
    sportId: 5,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'midwest',
    upvotes: 18,
    comments: 6,
    shares: 2,
    views: 987,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['training', 'serve-accuracy', 'varsity'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 21600000).toISOString(), // 6 hours ago
  },
  {
    id: '4', // Matches dashboard post ID
    videoUrl: '/tennis-player-hitting-backhand-slice.mp4',
    thumbnailUrl: '/tennis-player-hitting-backhand-slice.png',
    caption: 'Backhand slice technique finally clicking! Thanks to everyone who gave tips last week 🎾',
    athleteId: 'user4',
    athleteName: 'Emma Wilson',
    athleteUsername: 'emma_wilson',
    athleteAvatar: '/diverse-user-avatars.png',
    athleteAge: 17,
    athleteLocation: 'Central Tennis Club',
    sport: 'Tennis',
    sportId: 6,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'south',
    upvotes: 27,
    comments: 9,
    shares: 4,
    views: 1543,
    hasUpvoted: true,
    isBookmarked: false,
    tags: ['training', 'backhand', 'technique'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
  },
  // ADDITIONAL CLIPS TO REACH 25-30 TOTAL
  {
    id: 'clip-5',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: undefined,
    caption: 'Game-winning three-pointer at the buzzer! This is what championships are made of 🏆🔥',
    athleteId: 'athlete-1',
    athleteName: 'Jordan Mitchell',
    athleteUsername: 'jmitch_hoops',
    athleteAvatar: undefined,
    athleteAge: 17,
    athleteLocation: 'Chicago, IL',
    sport: 'Basketball',
    sportId: 1,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'midwest',
    upvotes: 12453,
    comments: 892,
    shares: 456,
    views: 89234,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'clutch', 'game-winning'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'clip-6',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: undefined,
    caption: 'Little league home run! This 8-year-old just hit his first homer and the whole team went wild! 💙⚾',
    athleteId: 'athlete-2',
    athleteName: 'Tommy Anderson',
    athleteUsername: 'tommy_slugger',
    athleteAvatar: undefined,
    athleteAge: 8,
    athleteLocation: 'Dallas, TX',
    sport: 'Baseball',
    sportId: 2,
    contentRating: 'wholesome',
    isWholesome: true,
    sportLevel: 'little_league',
    region: 'southwest',
    upvotes: 45678,
    comments: 2341,
    shares: 1892,
    views: 234567,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['wholesome', 'highlight', 'rookie'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'clip-7',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: undefined,
    caption: '🔥 Check out the new Nike Air training shoes - designed for explosive performance! Get yours now.',
    athleteId: 'sponsor-1',
    athleteName: 'Nike Basketball',
    athleteUsername: 'nike',
    athleteAvatar: undefined,
    sport: 'Basketball',
    contentRating: 'sfw',
    isWholesome: false,
    upvotes: 8234,
    comments: 423,
    shares: 678,
    views: 156789,
    hasUpvoted: false,
    isBookmarked: false,
    tags: [],
    isSponsored: true,
    sponsorName: 'Nike',
    sponsorLogo: undefined,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'clip-8',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: undefined,
    caption: 'NCAA Championship moment! The final seconds of overtime - pure intensity 💪🏀',
    athleteId: 'athlete-3',
    athleteName: 'Sarah Williams',
    athleteUsername: 'swilliams_ball',
    athleteAvatar: undefined,
    athleteAge: 21,
    athleteLocation: 'Durham, NC',
    sport: 'Basketball',
    sportId: 1,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'college',
    region: 'south',
    upvotes: 23456,
    comments: 1234,
    shares: 891,
    views: 345678,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'clutch', 'college'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'clip-9',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: undefined,
    caption: 'MMA training session - working on that knockout power! This is how champions are built 🥊💥',
    athleteId: 'athlete-4',
    athleteName: 'Marcus "Thunder" Thompson',
    athleteUsername: 'thunder_mma',
    athleteAvatar: undefined,
    athleteAge: 28,
    athleteLocation: 'Las Vegas, NV',
    sport: 'MMA',
    sportId: 7,
    contentRating: 'nsfw',
    isWholesome: false,
    sportLevel: 'professional',
    region: 'west',
    upvotes: 34567,
    comments: 2156,
    shares: 1234,
    views: 567890,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['training', 'mma', 'professional'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: 'clip-10',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: undefined,
    caption: 'Skateboarding fail compilation - we all start somewhere! Keep pushing 🛹😅',
    athleteId: 'athlete-5',
    athleteName: 'Jake Peterson',
    athleteUsername: 'jake_skates',
    athleteAvatar: undefined,
    athleteAge: 15,
    athleteLocation: 'San Diego, CA',
    sport: 'Skateboarding',
    sportId: 8,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'youth',
    region: 'west',
    upvotes: 18923,
    comments: 1456,
    shares: 789,
    views: 234567,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['funny', 'fail', 'training'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: 'clip-11',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: undefined,
    caption: 'High school soccer championship - the winning goal! What a season! ⚽🏆',
    athleteId: 'athlete-6',
    athleteName: 'Sofia Martinez',
    athleteUsername: 'sofia_soccer',
    athleteAvatar: undefined,
    athleteAge: 16,
    athleteLocation: 'Miami, FL',
    sport: 'Soccer',
    sportId: 3,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'south',
    upvotes: 29345,
    comments: 1789,
    shares: 1023,
    views: 456789,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'game-winning', 'champion'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 25200000).toISOString(),
  },
  {
    id: 'clip-12',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: undefined,
    caption: 'Athlete with Down syndrome scores first basket! The entire gym erupted - this is what sports is about ❤️🏀',
    athleteId: 'athlete-7',
    athleteName: 'David Chen',
    athleteUsername: 'david_hoops',
    athleteAvatar: undefined,
    athleteAge: 14,
    athleteLocation: 'Seattle, WA',
    sport: 'Basketball',
    sportId: 1,
    contentRating: 'wholesome',
    isWholesome: true,
    sportLevel: 'middle_school',
    region: 'west',
    upvotes: 89234,
    comments: 5678,
    shares: 12345,
    views: 1234567,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['wholesome', 'highlight', 'inspiring'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: 'clip-13',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: undefined,
    caption: 'NFL Sunday highlights - that catch was absolutely INSANE! 🏈🔥',
    athleteId: 'athlete-8',
    athleteName: 'Tyrone Jackson',
    athleteUsername: 'tyrone_wr',
    athleteAvatar: undefined,
    athleteAge: 26,
    athleteLocation: 'Green Bay, WI',
    sport: 'Football',
    sportId: 4,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'professional',
    region: 'midwest',
    upvotes: 67890,
    comments: 3456,
    shares: 2345,
    views: 890123,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'clutch', 'professional'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 32400000).toISOString(),
  },
  {
    id: 'clip-14',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    thumbnailUrl: undefined,
    caption: 'College volleyball championship point - the entire season came down to this! 🏐💪',
    athleteId: 'athlete-9',
    athleteName: 'Emily Parker',
    athleteUsername: 'emily_vball',
    athleteAvatar: undefined,
    athleteAge: 20,
    athleteLocation: 'Stanford, CA',
    sport: 'Volleyball',
    sportId: 5,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'college',
    region: 'west',
    upvotes: 34567,
    comments: 1890,
    shares: 1123,
    views: 456789,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'clutch', 'college'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 36000000).toISOString(),
  },
  {
    id: 'clip-15',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: undefined,
    caption: 'Track and field training - working on my sprint starts! Coach says my form is finally locked in 🏃‍♂️💨',
    athleteId: 'athlete-10',
    athleteName: 'Jamal Williams',
    athleteUsername: 'jamal_track',
    athleteAvatar: undefined,
    athleteAge: 18,
    athleteLocation: 'Atlanta, GA',
    sport: 'Track',
    sportId: 9,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'south',
    upvotes: 15234,
    comments: 678,
    shares: 345,
    views: 123456,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['training', 'track', 'sprint'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 39600000).toISOString(),
  },
  {
    id: 'clip-16',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: undefined,
    caption: 'Swimming practice - perfecting my butterfly stroke! Made it under 60 seconds for the first time 🏊‍♀️',
    athleteId: 'athlete-11',
    athleteName: 'Olivia Chen',
    athleteUsername: 'olivia_swims',
    athleteAvatar: undefined,
    athleteAge: 16,
    athleteLocation: 'Austin, TX',
    sport: 'Swimming',
    sportId: 10,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'southwest',
    upvotes: 21456,
    comments: 892,
    shares: 456,
    views: 198765,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['training', 'swimming', 'personal-record'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'clip-17',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: undefined,
    caption: 'Lacrosse scrimmage highlight - best assist of my career! Chemistry with teammates is unreal 🥍',
    athleteId: 'athlete-12',
    athleteName: 'Connor Murphy',
    athleteUsername: 'connor_lax',
    athleteAvatar: undefined,
    athleteAge: 17,
    athleteLocation: 'Boston, MA',
    sport: 'Lacrosse',
    sportId: 11,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'northeast',
    upvotes: 18765,
    comments: 543,
    shares: 287,
    views: 145678,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'assist', 'teamwork'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 46800000).toISOString(),
  },
  {
    id: 'clip-18',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: undefined,
    caption: 'Gymnast nails perfect 10 on floor routine! Years of practice paying off 🤸‍♀️✨',
    athleteId: 'athlete-13',
    athleteName: 'Isabella Garcia',
    athleteUsername: 'bella_gymnastics',
    athleteAvatar: undefined,
    athleteAge: 15,
    athleteLocation: 'Denver, CO',
    sport: 'Gymnastics',
    sportId: 12,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'west',
    upvotes: 56789,
    comments: 3421,
    shares: 2134,
    views: 678901,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'perfect-score', 'gymnastics'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 50400000).toISOString(),
  },
  {
    id: 'clip-19',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: undefined,
    caption: 'Rugby tackle technique training - hitting hard but staying safe! 🏉💪',
    athleteId: 'athlete-14',
    athleteName: 'Liam O\'Brien',
    athleteUsername: 'liam_rugby',
    athleteAvatar: undefined,
    athleteAge: 19,
    athleteLocation: 'Portland, OR',
    sport: 'Rugby',
    sportId: 13,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'college',
    region: 'west',
    upvotes: 14567,
    comments: 789,
    shares: 421,
    views: 112345,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['training', 'tackle', 'technique'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 54000000).toISOString(),
  },
  {
    id: 'clip-20',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: undefined,
    caption: 'Hockey breakaway goal in overtime! Whole arena went crazy 🏒🚨',
    athleteId: 'athlete-15',
    athleteName: 'Noah Anderson',
    athleteUsername: 'noah_hockey',
    athleteAvatar: undefined,
    athleteAge: 17,
    athleteLocation: 'Minneapolis, MN',
    sport: 'Hockey',
    sportId: 14,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'midwest',
    upvotes: 43210,
    comments: 2345,
    shares: 1456,
    views: 567890,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'overtime', 'clutch'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 57600000).toISOString(),
  },
  {
    id: 'clip-21',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: undefined,
    caption: 'Crossfit competition PR! Hit a new snatch record today 🏋️‍♂️🔥',
    athleteId: 'athlete-16',
    athleteName: 'Ethan Brooks',
    athleteUsername: 'ethan_fitness',
    athleteAvatar: undefined,
    athleteAge: 24,
    athleteLocation: 'San Francisco, CA',
    sport: 'Crossfit',
    sportId: 15,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'amateur',
    region: 'west',
    upvotes: 19876,
    comments: 1023,
    shares: 678,
    views: 234567,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['training', 'personal-record', 'strength'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 61200000).toISOString(),
  },
  {
    id: 'clip-22',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: undefined,
    caption: 'Cheerleading nationals - our pyramid was flawless! Team gold medal 🥇📣',
    athleteId: 'athlete-17',
    athleteName: 'Mia Thompson',
    athleteUsername: 'mia_cheer',
    athleteAvatar: undefined,
    athleteAge: 16,
    athleteLocation: 'Dallas, TX',
    sport: 'Cheerleading',
    sportId: 16,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'south',
    upvotes: 38901,
    comments: 1987,
    shares: 1234,
    views: 456789,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'competition', 'champion'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 64800000).toISOString(),
  },
  {
    id: 'clip-23',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: undefined,
    caption: 'Rock climbing - finally conquered that V8 route! My fingers are dead but so worth it 🧗‍♂️',
    athleteId: 'athlete-18',
    athleteName: 'Lucas Martinez',
    athleteUsername: 'lucas_climbs',
    athleteAvatar: undefined,
    athleteAge: 22,
    athleteLocation: 'Boulder, CO',
    sport: 'Climbing',
    sportId: 17,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'amateur',
    region: 'west',
    upvotes: 27654,
    comments: 1345,
    shares: 876,
    views: 298765,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'achievement', 'climbing'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 68400000).toISOString(),
  },
  {
    id: 'clip-24',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    thumbnailUrl: undefined,
    caption: 'Baseball pitcher perfect game! 27 up, 27 down. Dream come true ⚾🎯',
    athleteId: 'athlete-19',
    athleteName: 'Ryan Foster',
    athleteUsername: 'ryan_pitcher',
    athleteAvatar: undefined,
    athleteAge: 18,
    athleteLocation: 'Phoenix, AZ',
    sport: 'Baseball',
    sportId: 2,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'high_school',
    region: 'southwest',
    upvotes: 52341,
    comments: 2987,
    shares: 1876,
    views: 623456,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'perfect-game', 'historic'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 72000000).toISOString(),
  },
  {
    id: 'clip-25',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: undefined,
    caption: 'Martial arts tournament - winning the gold with a spinning kick knockout! 🥋💥',
    athleteId: 'athlete-20',
    athleteName: 'Sophia Kim',
    athleteUsername: 'sophia_taekwondo',
    athleteAvatar: undefined,
    athleteAge: 17,
    athleteLocation: 'Los Angeles, CA',
    sport: 'Taekwondo',
    sportId: 18,
    contentRating: 'sfw',
    isWholesome: false,
    sportLevel: 'amateur',
    region: 'west',
    upvotes: 41234,
    comments: 2156,
    shares: 1345,
    views: 512345,
    hasUpvoted: false,
    isBookmarked: false,
    tags: ['highlight', 'knockout', 'champion'],
    isSponsored: false,
    createdAt: new Date(Date.now() - 75600000).toISOString(),
  },
]
